[workspace]
resolver = "2"
members = ["console-bff-core", "tenant-bff", "operator-bff"]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
async-trait = "0.1"
axum = "0.8"
console-bff-core = { path = "console-bff-core" }
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
time = { version = "0.3", features = ["formatting", "serde"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["limit", "trace", "compression-full", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1", features = ["v4", "serde"] }

[profile.release]
lto = "thin"
codegen-units = 1
